---

- name: Найти все домашние папки пользователей в /home
  ansible.builtin.find:
    paths: /home
    file_type: directory
    recurse: false
  register: found_homes

- name: Скопировать конфигурационные файлы в каждую найденную папку
  ansible.builtin.template:
    src: "{{ item.1 }}.j2"
    dest: "{{ item.0.path }}/{{ item.1 }}"
    owner: "{{ item.0.path | basename }}"
    group: "{{ item.0.path | basename }}"
    mode: '0644'
    backup: true
  loop: "{{ found_homes.files | product(['.bashrc', '.nanorc', '.vimrc']) | list }}"
  when: found_homes.files | length > 0

...
