---

- name: Установить текстовые редакторы
  ansible.builtin.package:
    name:
      - nano
      - vim
      - gedit
      - kate
      - neovim
    state: latest
  when: ansible_facts['os_family'] == "Debian"

...