---

- name: Установить общие пакеты для работы с Apple-устройствами
  ansible.builtin.package:
    name:
      - usbmuxd
      - libimobiledevice-utils
      - libusbmuxd-tools
      - ifuse
      - uxplay
    state: latest
  when: ansible_facts['os_family'] == "Debian"

...