---

- name: Установить сетевые утилиты
  ansible.builtin.package:
    name:
      - net-tools
      - curl
      - wget
      - nmap
      - traceroute
      - mtr
      - tcpdump
      - iperf3
    state: latest
  when: ansible_facts['os_family'] == "Debian"

...