---

- name: Установить инструменты безопасности
  ansible.builtin.package:
    name:
      - fail2ban
      - ufw
      - clamav
      - rkhunter
      - lynis
    state: latest
  when: ansible_facts['os_family'] == "Debian"

...