---

- name: Установить дополнительные утилиты для администрирования
  ansible.builtin.package:
    name:
      - rsync
      - screen
      - ncdu
      - iotop
      - lsof
      - strace
      - sysstat
      - smartmontools
    state: latest
  when: ansible_facts['os_family'] == "Debian"

...