---

- name: Установить утилиты командной строки 
  ansible.builtin.package:
    name:
      - tmux
      - mc
      - konsole
      - htop
      - tree
    state: latest
  when: ansible_facts['os_family'] == "Debian"

...